spring:
  # ===============================
  # DATABASE — LOCAL
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/coworking
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true

# ===============================
# LOGGING (DEV — más verboso)
# ===============================
logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[org.flywaydb]": INFO

# ===============================
# APP CUSTOM PROPERTIES
# ===============================
app:
  jwt:
    secret: dev-secret-key-banco-cuscatlan-2026-must-be-at-least-256-bits-long
    expiration: 86400000   # 24 horas en ms
  cache:
    ttl: 3600              # segundos
  payment:
    base-url: http://localhost:8080
    validate-path: /mock/payments/validate

# ===============================
# RESILIENCE4J
# ===============================
resilience4j:
  circuitbreaker:
    instances:
      paymentValidation:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 500ms
  timelimiter:
    instances:
      paymentValidation:
        timeoutDuration: 2s
      default:
        timeoutDuration: 5s
